In [15]:
# 9.4
# univariate data preparation
from numpy import array

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
print(X.shape)
for i in range(len(X)):
	print(X[i], y[i])

(6, 3)
[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [18]:
# 9.10
# univariate lstm example
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] 
# into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X)

[[[10]
  [20]
  [30]]

 [[20]
  [30]
  [40]]

 [[30]
  [40]
  [50]]

 [[40]
  [50]
  [60]]

 [[50]
  [60]
  [70]]

 [[60]
  [70]
  [80]]]


In [20]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', 
	input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=100, verbose=0)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
print(x_input)

[[[70]
  [80]
  [90]]]


In [21]:
yhat = model.predict(x_input, verbose=1)
print(yhat)

1/1 [==============================] - 0s 1ms/step
[[106.90549]]


In [3]:
# 9.13
# univariate stacked lstm example
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

# split a univariate sequence
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] 
# into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True,
 	input_shape=(n_steps,n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=400, verbose=1)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Epoch 1/400
1/1 [==============================] - 0s 2ms/step - loss: 4490.7446
Epoch 2/400
1/1 [==============================] - 0s 2ms/step - loss: 4475.1743
Epoch 3/400
1/1 [==============================] - 0s 4ms/step - loss: 4459.5322
Epoch 4/400
1/1 [==============================] - 0s 4ms/step - loss: 4444.4487
Epoch 5/400
1/1 [==============================] - 0s 3ms/step - loss: 4429.3735
Epoch 6/400
1/1 [==============================] - 0s 2ms/step - loss: 4413.7495
Epoch 7/400
1/1 [==============================] - 0s 5ms/step - loss: 4397.3804
Epoch 8/400
1/1 [==============================] - 0s 5ms/step - loss: 4380.0288
Epoch 9/400
1/1 [==============================] - 0s 5ms/step - loss: 4361.5991
Epoch 10/400
1/1 [==============================] - 0s 2ms/step - loss: 4341.8857
Epoch 11/400
1/1 [==============================] - 0s 4ms/step - loss: 4320.5630
Epoch 12/400
1/1 [==============================] - 0s 2ms/step - loss: 4296.7510
Epoch 13/400
1/1 [=======

In [4]:
# 9.16
# univariate bidirectional lstm example
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

# split a univariate sequence
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=400, verbose=1)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Epoch 1/400
1/1 [==============================] - 0s 2ms/step - loss: 3932.8049
Epoch 2/400
1/1 [==============================] - 0s 4ms/step - loss: 3859.2930
Epoch 3/400
1/1 [==============================] - 0s 6ms/step - loss: 3784.9902
Epoch 4/400
1/1 [==============================] - 0s 14ms/step - loss: 3709.5642
Epoch 5/400
1/1 [==============================] - 0s 2ms/step - loss: 3632.6199
Epoch 6/400
1/1 [==============================] - 0s 2ms/step - loss: 3553.8132
Epoch 7/400
1/1 [==============================] - 0s 4ms/step - loss: 3472.8792
Epoch 8/400
1/1 [==============================] - 0s 4ms/step - loss: 3389.5234
Epoch 9/400
1/1 [==============================] - 0s 4ms/step - loss: 3303.4788
Epoch 10/400
1/1 [==============================] - 0s 4ms/step - loss: 3214.5293
Epoch 11/400
1/1 [==============================] - 0s 2ms/step - loss: 3122.4866
Epoch 12/400
1/1 [==============================] - 0s 2ms/step - loss: 3027.2930
Epoch 13/400
1/1 [======

In [22]:
# 9.21
# univariate cnn lstm example
from numpy import array

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import TimeDistributed
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import MaxPooling1D

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 4
# split into samples
X, y = split_sequence(raw_seq, n_steps)
print(X)

[[10 20 30 40]
 [20 30 40 50]
 [30 40 50 60]
 [40 50 60 70]
 [50 60 70 80]]


In [23]:
# reshape from [samples, timesteps] 
# into [samples, subsequences, timesteps, features]
n_features = 1
n_seq = 2
n_steps = 2
X = X.reshape((X.shape[0], n_seq, n_steps, n_features))
print(X)

[[[[10]
   [20]]

  [[30]
   [40]]]


 [[[20]
   [30]]

  [[40]
   [50]]]


 [[[30]
   [40]]

  [[50]
   [60]]]


 [[[40]
   [50]]

  [[60]
   [70]]]


 [[[50]
   [60]]

  [[70]
   [80]]]]


In [24]:
# define model
model = Sequential()
model.add(TimeDistributed(Conv1D(64, 1, activation='relu'), input_shape=(None, n_steps,n_features)))
model.add(TimeDistributed(MaxPooling1D()))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=100, verbose=0)
# demonstrate prediction
x_input = array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, n_steps, n_features))
print(x_input)
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[[[60]
   [70]]

  [[80]
   [90]]]]
[[104.64876]]


In [8]:
# 9.25
# одномерный пример convlstm
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import ConvLSTM2D

# разделить одномерную последовательность на образцы
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# найти конец этой модели
		end_ix = i + n_steps
		# проверь, находимся ли мы вне последовательности
		if end_ix > len(sequence)-1:
			break
		# собрать входные и выходные части шаблона
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# определить последовательность ввода
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# выберите количество временных шагов
n_steps = 4
# разделить на образцы
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] 
# into [samples, timesteps, rows, columns, features]
n_features = 1
n_seq = 2
n_steps = 2
X = X.reshape((X.shape[0], n_seq, 1, n_steps, n_features))
# определить модель
model = Sequential()
model.add(ConvLSTM2D(64, (1,2), activation='relu', 
	input_shape=(n_seq, 1, n_steps,n_features)))
model.add(Flatten())
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=500, verbose=1)
# демонстрировать прогноз
x_input = array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, 1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Epoch 1/500
1/1 [==============================] - 0s 2ms/step - loss: 5310.5034
Epoch 2/500
1/1 [==============================] - 0s 2ms/step - loss: 5172.5439
Epoch 3/500
1/1 [==============================] - 0s 2ms/step - loss: 5039.0210
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 4909.1128
Epoch 5/500
1/1 [==============================] - 0s 4ms/step - loss: 4779.3174
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 4652.0918
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 4527.2476
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 4406.1128
Epoch 9/500
1/1 [==============================] - 0s 12ms/step - loss: 4287.9717
Epoch 10/500
1/1 [==============================] - 0s 4ms/step - loss: 4172.4395
Epoch 11/500
1/1 [==============================] - 0s 2ms/step - loss: 4056.5808
Epoch 12/500
1/1 [==============================] - 0s 2ms/step - loss: 3937.7278
Epoch 13/500
1/1 [======

In [9]:
# 9.29
# multivariate data preparation
from numpy import array
from numpy import hstack
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [12]:
# 9.34
# multivariate data preparation
from numpy import array
from numpy import hstack
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [13]:
# 9.39
# multivariate lstm example
from numpy import array
from numpy import hstack
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=1)
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Epoch 1/200
1/1 [==============================] - 0s 2ms/step - loss: 14233.1807
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 13727.0146
Epoch 3/200
1/1 [==============================] - 0s 3ms/step - loss: 13258.4209
Epoch 4/200
1/1 [==============================] - 0s 5ms/step - loss: 12810.0723
Epoch 5/200
1/1 [==============================] - 0s 4ms/step - loss: 12370.6660
Epoch 6/200
1/1 [==============================] - 0s 5ms/step - loss: 11927.2666
Epoch 7/200
1/1 [==============================] - 0s 4ms/step - loss: 11470.0615
Epoch 8/200
1/1 [==============================] - 0s 2ms/step - loss: 10996.7588
Epoch 9/200
1/1 [==============================] - 0s 9ms/step - loss: 10498.6777
Epoch 10/200
1/1 [==============================] - 0s 2ms/step - loss: 9962.3887
Epoch 11/200
1/1 [==============================] - 0s 2ms/step - loss: 9371.9297
Epoch 12/200
1/1 [==============================] - 0s 3ms/step - loss: 8718.6338
Epoch 13/200
1/1

In [14]:
# 9.51
# multivariate output stacked lstm example
from numpy import array
from numpy import hstack
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
# define model
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps,n_features)))
model.add(LSTM(100, activation='relu'))
model.add(Dense(n_features))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=400, verbose=1)
# demonstrate prediction
x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

Epoch 1/400
1/1 [==============================] - 0s 4ms/step - loss: 9589.2607
Epoch 2/400
1/1 [==============================] - 0s 4ms/step - loss: 9401.8818
Epoch 3/400
1/1 [==============================] - 0s 2ms/step - loss: 9242.7451
Epoch 4/400
1/1 [==============================] - 0s 2ms/step - loss: 9083.0830
Epoch 5/400
1/1 [==============================] - 0s 3ms/step - loss: 8894.6396
Epoch 6/400
1/1 [==============================] - 0s 2ms/step - loss: 8666.9258
Epoch 7/400
1/1 [==============================] - 0s 6ms/step - loss: 8402.7402
Epoch 8/400
1/1 [==============================] - 0s 2ms/step - loss: 8104.7524
Epoch 9/400
1/1 [==============================] - 0s 8ms/step - loss: 7765.0493
Epoch 10/400
1/1 [==============================] - 0s 4ms/step - loss: 7377.1147
Epoch 11/400
1/1 [==============================] - 0s 4ms/step - loss: 6927.6802
Epoch 12/400
1/1 [==============================] - 0s 2ms/step - loss: 6402.3540
Epoch 13/400
1/1 [=======